-- Sprint 7 — Extra constraints to run after prisma migrate dev
-- Apply via: psql $DATABASE_URL -f sprint7_constraints.sql
-- Or paste into the migration SQL file generated by T1.7

-- Functional UNIQUE on std_product: (template_id, grade_id, attribute_values canonical)
-- Prevents duplicate catalog entries for the same template + grade + attribute set.
-- Uses jsonb_path_ops for @> containment query performance.
CREATE UNIQUE INDEX IF NOT EXISTS ux_std_product_catalog
  ON std_product (template_id, grade_id, (attribute_values::text));

-- GIN index using jsonb_path_ops on std_product.attribute_values
-- (Prisma creates jsonb_ops GIN by default; this adds the faster path-ops variant)
CREATE INDEX IF NOT EXISTS gin_std_product_attr_path
  ON std_product USING GIN (attribute_values jsonb_path_ops);

CREATE INDEX IF NOT EXISTS gin_part_attr_path
  ON part USING GIN (attribute_values jsonb_path_ops);

CREATE INDEX IF NOT EXISTS gin_material_line_attr_path
  ON material_line USING GIN (attribute_values jsonb_path_ops);
