-- This migration was auto-generated by Prisma during Sprint 4.3 history table setup.
-- The FK renames and constraint re-adds it originally contained have already been
-- applied to the live database via the adjacent 20260429180000 migration.
-- Replaced with no-op to keep shadow-DB replay stable across migration order.
SELECT 1;
